import HurtadoZeta23.ShiftedPinching
import HurtadoZeta23.Endgame
import HurtadoZeta23.ZetaRvMBridge
import Mathlib.Tactic

noncomputable section

open Filter Asymptotics

namespace HurtadoZeta23

/-- Concrete counting functions used by the final asymptotic assembly. -/
def globalN (T : ℝ) : ℝ :=
  (Zeta23.Ncount T (2 * T) : ℝ)

def globalS (T : ℝ) : ℝ :=
  (Zeta23.N0simple T (2 * T) : ℝ)

/--
Asymptotic data supplied by shifted block pinching.

`retained` is the central retained simple-zero count,
`defect` is the retained Gram defect, and `span` is the retained normalized
ordinate span.

The three error functions record boundary loss, span/RvM error, and the
accumulated uniform block error.
-/
structure ShiftedPinchingAsymptotics where
  retained : ℝ → ℝ
  defect : ℝ → ℝ
  span : ℝ → ℝ

  retainedLoss : ℝ → ℝ
  spanErr : ℝ → ℝ
  blockErr : ℝ → ℝ

  retainedLoss_small :
    retainedLoss =o[atTop] globalN

  spanErr_small :
    spanErr =o[atTop] globalN

  blockErr_small :
    blockErr =o[atTop] globalN

  retained_bound :
    ∀ᶠ T in atTop,
      globalS T - retainedLoss T ≤ retained T

  span_bound :
    ∀ᶠ T in atTop,
      span T ≤ globalN T + spanErr T

  pinching_bound :
    ∀ᶠ T in atTop,
      alpha * retained T
        - pressureCost * span T
        - endpointCorrection
        - blockErr T
        ≤ defect T

/--
The stability-enhanced Montgomery--Taylor baseline with the retained Gram
defect left visible:

`S ≥ H_MT N + D(M') - o(N)`.
-/
structure BaselineWithDefect
    (defect : ℝ → ℝ) where

  err : ℝ → ℝ

  err_small :
    err =o[atTop] globalN

  bound :
    ∀ᶠ T in atTop,
      HMT * globalN T
        + defect T
        - err T
        ≤ globalS T

/--
The exact aggregate error generated by shifted pinching.
-/
def pinchingError
    (h : ShiftedPinchingAsymptotics)
    (T : ℝ) : ℝ :=
  alpha * h.retainedLoss T
    + pressureCost * h.spanErr T
    + endpointCorrection
    + h.blockErr T

/--
The constant endpoint correction is negligible with respect to `globalN`.
-/
lemma endpointCorrection_isLittleO_globalN :
    (fun _ : ℝ => endpointCorrection)
      =o[atTop]
    globalN := by
  change
    (fun _ : ℝ => endpointCorrection)
      =o[atTop]
    zetaDyadicN
  exact endpointCorrection_isLittleO_zetaDyadicN

/--
Every constituent of the pinching error is `o(N)`, hence so is their sum.
-/
theorem pinchingError_small
    (h : ShiftedPinchingAsymptotics) :
    pinchingError h
      =o[atTop]
    globalN := by

  unfold pinchingError

  have hret :
      (fun T : ℝ =>
        alpha * h.retainedLoss T)
        =o[atTop]
      globalN := by
    exact
      h.retainedLoss_small.const_mul_left alpha

  have hspan :
      (fun T : ℝ =>
        pressureCost * h.spanErr T)
        =o[atTop]
      globalN := by
    exact
      h.spanErr_small.const_mul_left pressureCost

  have hend :
      (fun _ : ℝ => endpointCorrection)
        =o[atTop]
      globalN :=
    endpointCorrection_isLittleO_globalN

  have h1 :
      (fun T : ℝ =>
        alpha * h.retainedLoss T
          + pressureCost * h.spanErr T)
        =o[atTop]
      globalN := by
    exact hret.add hspan

  have h2 :
      (fun T : ℝ =>
        alpha * h.retainedLoss T
          + pressureCost * h.spanErr T
          + endpointCorrection)
        =o[atTop]
      globalN := by
    exact h1.add hend

  exact h2.add h.blockErr_small

/--
Shifted pinching, the retained-set estimate, and the Riemann--von Mangoldt
span estimate combine to the global defect lower bound

`D(M') ≥ α N₀ˢ - pressureCost N - o(N)`.
-/
theorem defect_global_from_shifted_pinching
    (h : ShiftedPinchingAsymptotics) :
    ∀ᶠ T in atTop,
      alpha * globalS T
        - pressureCost * globalN T
        - pinchingError h T
        ≤ h.defect T := by

  have ha :
      0 ≤ alpha := by
    norm_num [alpha]

  have hp :
      0 ≤ pressureCost := by
    norm_num [pressureCost]

  filter_upwards
    [
      h.retained_bound,
      h.span_bound,
      h.pinching_bound
    ]
    with T hret hspan hpinch

  have hret' :
      alpha * (globalS T - h.retainedLoss T)
        ≤
      alpha * h.retained T := by
    exact
      mul_le_mul_of_nonneg_left
        hret
        ha

  have hspan' :
      pressureCost * h.span T
        ≤
      pressureCost * (globalN T + h.spanErr T) := by
    exact
      mul_le_mul_of_nonneg_left
        hspan
        hp

  unfold pinchingError

  linarith

/--
Total error after inserting the defect lower bound into the baseline.
-/
def assembledError
    (p : ShiftedPinchingAsymptotics)
    (b : BaselineWithDefect p.defect)
    (T : ℝ) : ℝ :=
  b.err T + pinchingError p T

/--
The total assembled error remains `o(globalN)`.
-/
lemma assembledError_small
    (p : ShiftedPinchingAsymptotics)
    (b : BaselineWithDefect p.defect) :
    assembledError p b
      =o[atTop]
    globalN := by

  unfold assembledError

  exact
    b.err_small.add
      (pinchingError_small p)

/--
Construct the final `GlobalRefinement` object from shifted pinching and the
baseline-with-defect estimate.

This is a `def`, not a `theorem`, because `GlobalRefinement` is a structure in
`Type`.
-/
def globalRefinement_of_pinching_and_baseline
    (p : ShiftedPinchingAsymptotics)
    (b : BaselineWithDefect p.defect) :
    GlobalRefinement := by

  refine
    {
      err := assembledError p b
      err_small := ?_
      bound := ?_
    }

  ·
    change
      assembledError p b
        =o[atTop]
      globalN

    exact
      assembledError_small p b

  ·
    have hdef :=
      defect_global_from_shifted_pinching p

    filter_upwards
      [b.bound, hdef]
      with T hbase hdefT

    change
      HMT * globalN T
        + alpha * globalS T
        - pressureCost * globalN T
        - assembledError p b T
        ≤
      globalS T

    unfold assembledError

    linarith

/--
Direct ε-form of the published theorem from the two genuine final inputs.
-/
theorem published_eps_form_of_pinching_and_baseline
    (p : ShiftedPinchingAsymptotics)
    (b : BaselineWithDefect p.defect) :
    ∀ ε > 0,
      ∃ T₀ : ℝ,
        ∀ T ≥ T₀,
          (publishedConstant - ε)
              * (Zeta23.Ncount T (2 * T) : ℝ)
            ≤
          Zeta23.N0simple T (2 * T) := by

  exact
    published_eps_form_from_global_refinement
      (globalRefinement_of_pinching_and_baseline p b)

end HurtadoZeta23