import HurtadoZeta23.RetainedCoreBridge
import Mathlib.Tactic
import Mathlib.Analysis.Asymptotics.Lemmas

noncomputable section

open Filter Asymptotics

namespace HurtadoZeta23

/-- Sampling scale appearing literally in the shifted-pinching argument:
`T/h = T*l(T)/(2π)`. -/
def samplingSpanScale (T : ℝ) : ℝ :=
  T * Zeta23.l T / (2 * Real.pi)

/-- Normalized coordinate difference associated with two ordinary ordinates. -/
def normalizedOrdinateSpan (T γ₁ γ₂ : ℝ) : ℝ :=
  Zeta23.l T / (2 * Real.pi) * (γ₂ - γ₁)

/-- Any two retained ordinates lying in `[T,2T]` have normalized span at most
`T*l(T)/(2π)`.  This is the geometric inequality used in the paper. -/
theorem normalizedOrdinateSpan_le_samplingSpanScale
    {T γ₁ γ₂ : ℝ}
    (_hT : 0 ≤ T)
    (hl : 0 ≤ Zeta23.l T)
    (h₁ : T ≤ γ₁)
    (h₂ : γ₂ ≤ 2 * T) :
    normalizedOrdinateSpan T γ₁ γ₂ ≤ samplingSpanScale T := by
  have hgap : γ₂ - γ₁ ≤ T := by linarith
  have hcoef : 0 ≤ Zeta23.l T / (2 * Real.pi) := by positivity
  unfold normalizedOrdinateSpan samplingSpanScale
  have hmul := mul_le_mul_of_nonneg_left hgap hcoef
  field_simp [Real.pi_ne_zero] at hmul ⊢
  nlinarith [Real.pi_pos]

/-- Difference between the exact sampling span scale and Zeta23's RvM main
scale.  Since `ell1 = l + (2 log 2 - 1)`, this is only `O(T)`. -/
def samplingToRvMErr (T : ℝ) : ℝ :=
  |samplingSpanScale T - rvmMainScale T|

/-- The sampling scale is bounded by the RvM main scale plus its canonical
sampling-to-RvM error. -/
theorem samplingSpanScale_le_rvmMain_add_err (T : ℝ) :
    samplingSpanScale T ≤ rvmMainScale T + samplingToRvMErr T := by
  unfold samplingToRvMErr
  have h := le_abs_self (samplingSpanScale T - rvmMainScale T)
  linarith

/-- Exact elementary formula for the sampling-to-RvM scale error. -/
theorem samplingToRvMErr_eq_const_mul_abs (T : ℝ) :
    samplingToRvMErr T =
      (|1 - 2 * Real.log 2| / (2 * Real.pi)) * |T| := by
  have hdiff :
      samplingSpanScale T - rvmMainScale T =
        T * (1 - 2 * Real.log 2) / (2 * Real.pi) := by
    unfold samplingSpanScale rvmMainScale
    rw [Zeta23.ell1]
    field_simp [Real.pi_ne_zero] <;> ring
  unfold samplingToRvMErr
  rw [hdiff, abs_div, abs_mul, abs_of_pos (by positivity : (0 : ℝ) < 2 * Real.pi)]
  ring

/-- Since `l(T) → +∞`, one has `1 = o(l(T))`. -/
theorem one_isLittleO_zeta_l :
    (fun _ : ℝ => (1 : ℝ)) =o[atTop] Zeta23.l := by
  rw [isLittleO_one_left_iff ℝ]
  have hnonneg :
      ∀ᶠ T : ℝ in atTop, 0 ≤ Zeta23.l T :=
    tendsto_zeta_l_atTop.eventually_ge_atTop 0
  have heq :
      Zeta23.l =ᶠ[atTop] (fun T : ℝ => ‖Zeta23.l T‖) := by
    filter_upwards [hnonneg] with T hT
    rw [Real.norm_eq_abs, abs_of_nonneg hT]
  exact tendsto_zeta_l_atTop.congr' heq

/-- Consequently `T = o(T*l(T))`. -/
theorem id_isLittleO_T_mul_zeta_l :
    (fun T : ℝ => T) =o[atTop] (fun T : ℝ => T * Zeta23.l T) := by
  have h :=
    (isBigO_refl (fun T : ℝ => T) atTop).mul_isLittleO
      one_isLittleO_zeta_l
  simpa using h

/-- The difference between `l` and `ell1` is constant, hence the induced scale
error is `O(T)` and therefore `o(T*l(T))`. -/
theorem samplingToRvMErr_small_TlogT :
    samplingToRvMErr =o[atTop] (fun T : ℝ => T * Zeta23.l T) := by
  have hO : samplingToRvMErr =O[atTop] (fun T : ℝ => T) := by
    refine IsBigO.of_bound
      (|1 - 2 * Real.log 2| / (2 * Real.pi)) ?_
    filter_upwards with T
    rw [Real.norm_eq_abs, Real.norm_eq_abs,
      samplingToRvMErr_eq_const_mul_abs]
    have hc :
        0 ≤ |1 - 2 * Real.log 2| / (2 * Real.pi) := by
      positivity
    rw [abs_of_nonneg (mul_nonneg hc (abs_nonneg T))]
  exact hO.trans_isLittleO id_isLittleO_T_mul_zeta_l

/-- Concrete span data: the first and last retained ordinates lie inside
`[T,2T]`.

This carries numerical functions, so it belongs to `Type`, not `Prop`. -/
structure RetainedSpanGeometry where
  firstOrd : ℝ → ℝ
  lastOrd : ℝ → ℝ
  first_in : ∀ᶠ T in atTop, T ≤ firstOrd T
  last_in : ∀ᶠ T in atTop, lastOrd T ≤ 2 * T
  ordered : ∀ᶠ T in atTop, firstOrd T ≤ lastOrd T

/-- The actual normalized span generated by retained ordinates. -/
def RetainedSpanGeometry.span (h : RetainedSpanGeometry) (T : ℝ) : ℝ :=
  normalizedOrdinateSpan T (h.firstOrd T) (h.lastOrd T)

/-- The complete span comparison with `N(T,2T)` is now derived from geometry
plus Zeta23's RvM formula; no caller-supplied span error is needed. -/
def RetainedSpanGeometry.toRvMSpanInputs (h : RetainedSpanGeometry) : RvMSpanInputs :=
  { span := h.span
    geomErr := samplingToRvMErr
    geom_bound := by
      have hl : ∀ᶠ T : ℝ in atTop, 0 ≤ Zeta23.l T :=
        tendsto_zeta_l_atTop.eventually_ge_atTop 0
      filter_upwards [h.first_in, h.last_in, hl, eventually_ge_atTop (0 : ℝ)]
        with T hfirst hlast hlT hT
      have hs :=
        normalizedOrdinateSpan_le_samplingSpanScale hT hlT hfirst hlast
      exact hs.trans (samplingSpanScale_le_rvmMain_add_err T)
    geomErr_small_TlogT := samplingToRvMErr_small_TlogT }

end HurtadoZeta23
